/**
 * GENERATED by scripts/sync-config.mjs from bridge.config.json. Do not edit.
 *
 * The extension cannot read files outside its own folder, so the product
 * identity is copied here. scripts/gate.mjs fails when this file and
 * bridge.config.json disagree.
 */

export const PRODUCT_NAME = "Agent Browser Bridge"
export const PRODUCT_TAGLINE = "Drive your real, logged-in browsers from any AI agent"
export const NATIVE_HOST_ID = "com.agent_browser_bridge.host"
export const SERVICE_NAME = "Agent Browser Bridge broker"
export const LAUNCHD_LABEL = "com.agent_browser_bridge.host.broker"
export const SYSTEMD_UNIT = "agent-browser-bridge-broker"
