/**
 * Product identity, read from bridge.config.json at the repo root.
 *
 * Every Node-side module imports its names from here. The extension cannot
 * read files outside its own folder, so it gets the same values through the
 * GENERATED extension/lib/config.js, written by scripts/sync-config.mjs and
 * checked by scripts/gate.mjs. If the two ever disagree the gate fails, which
 * is the only way a drift between "what the extension calls connectNative
 * with" and "what the installer registered" becomes visible before it presents
 * as "Specified native messaging host not found".
 *
 * Environment variables are deliberately NOT derived from the product name:
 * BRIDGE_DEBUG, BRIDGE_QUIET, BRIDGE_WATCH_PARENT, BRIDGE_NODE and BRIDGE_HOME
 * are fixed, so a rename never silently changes which variable a launcher or a
 * shim reads.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
export const CONFIG_FILE = path.join(REPO_ROOT, 'bridge.config.json')

/** The keys a valid config must carry, with the rule each value has to satisfy. */
export const CONFIG_SHAPE = Object.freeze({
  productName: /^\S.{0,79}$/,
  tagline: /^.{0,200}$/,
  // Chromium's native messaging host name rule: lowercase alphanumerics, dots
  // and underscores, no leading or trailing dot, no consecutive dots.
  nativeHostId: /^[a-z0-9_]+(\.[a-z0-9_]+)*$/,
  socketName: /^[a-z0-9][a-z0-9-]{0,63}$/,
  stateDirName: /^[a-z0-9][a-z0-9-]{0,63}$/,
  serviceName: /^\S.{0,79}$/,
  mcpServerName: /^[a-z0-9][a-z0-9-]{0,63}$/,
})

/**
 * Read and validate the config. Throws with a message naming the key, so a
 * broken config fails at import time in every process rather than as a bad
 * pipe name three hops away.
 */
export function loadConfig(file = CONFIG_FILE) {
  let raw
  try {
    raw = JSON.parse(fs.readFileSync(file, 'utf8'))
  } catch (err) {
    throw new Error(`Cannot read ${file}: ${err?.message || err}`)
  }
  const out = {}
  for (const [key, rule] of Object.entries(CONFIG_SHAPE)) {
    const value = raw[key]
    if (typeof value !== 'string' || !rule.test(value)) {
      throw new Error(`${file}: "${key}" is ${JSON.stringify(value)}, which does not match ${rule}`)
    }
    out[key] = value
  }
  return Object.freeze(out)
}

export const CONFIG = loadConfig()

export const PRODUCT_NAME = CONFIG.productName
export const PRODUCT_TAGLINE = CONFIG.tagline
export const NATIVE_HOST_ID = CONFIG.nativeHostId
export const SOCKET_NAME = CONFIG.socketName
export const STATE_DIR_NAME = CONFIG.stateDirName
export const SERVICE_NAME = CONFIG.serviceName
export const MCP_SERVER_NAME = CONFIG.mcpServerName

/** launchd label on macOS. Reverse-DNS, like the host id it extends. */
export const LAUNCHD_LABEL = `${NATIVE_HOST_ID}.broker`
/** systemd user unit name on Linux. */
export const SYSTEMD_UNIT = `${STATE_DIR_NAME}-broker`

/**
 * The exact text of extension/lib/config.js for the current config. Kept here
 * so the generator and the gate cannot disagree about what "in sync" means.
 */
export function renderExtensionConfig(config = CONFIG) {
  const j = (v) => JSON.stringify(v)
  return [
    '/**',
    ' * GENERATED by scripts/sync-config.mjs from bridge.config.json. Do not edit.',
    ' *',
    ' * The extension cannot read files outside its own folder, so the product',
    ' * identity is copied here. scripts/gate.mjs fails when this file and',
    ' * bridge.config.json disagree.',
    ' */',
    '',
    `export const PRODUCT_NAME = ${j(config.productName)}`,
    `export const PRODUCT_TAGLINE = ${j(config.tagline)}`,
    `export const NATIVE_HOST_ID = ${j(config.nativeHostId)}`,
    `export const SERVICE_NAME = ${j(config.serviceName)}`,
    `export const LAUNCHD_LABEL = ${j(`${config.nativeHostId}.broker`)}`,
    `export const SYSTEMD_UNIT = ${j(`${config.stateDirName}-broker`)}`,
    '',
  ].join('\n')
}
